languageCode = 'en-us'
title = 'The Privacy Backplane Project'
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
repoURL = 'https://github.com/michaelpolinski/pb-website'
description = 'Privacy Backplane: exploring a legal-technical framework for individualized privacy policies in IoT environments'
colorDark = '#121212'
colorLight = '#f7f7f7'
colorDarkAccent = '#90CAF9'
colorLightAccent = '#1565C0'
images = ['android-chrome-512x512.png']
